import React, { useState, useEffect } from 'react';
import { 
  Stethoscope, 
  RefreshCw, 
  User, 
  Clock, 
  AlertTriangle, 
  CheckCircle2, 
  Printer, 
  FileText, 
  ChevronRight,
  ShieldAlert,
  Edit3
} from 'lucide-react';

export default function DoctorSummaryView({ tokens, onRefreshTokens }) {
  const [selectedToken, setSelectedToken] = useState(tokens?.[0] || null);
  const [physicianNotes, setPhysicianNotes] = useState('');
  const [consultationDone, setConsultationDone] = useState(false);

  useEffect(() => {
    if (!selectedToken && tokens?.length > 0) {
      setSelectedToken(tokens[0]);
    }
  }, [tokens, selectedToken]);

  const handleSelect = (t) => {
    setSelectedToken(t);
    setConsultationDone(false);
    setPhysicianNotes('');
  };

  const handleFinishConsult = () => {
    setConsultationDone(true);
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      
      {/* Top Bar */}
      <div className="p-5 sm:p-6 rounded-3xl border bg-slate-900/60 border-slate-800 light:bg-white light:border-slate-200 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
              <span className="text-xs font-bold uppercase tracking-wider text-emerald-400">
                Doctor Consultation Station • OPD Room 2
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-white light:text-slate-900">
              Physician OPD Queue & Pre-Elicited Histories
            </h2>
            <p className="text-xs sm:text-sm text-slate-400 light:text-slate-600 mt-1">
              Pre-intake clinical histories generated by MediKiosk kiosks. Review complete complaints in seconds instead of minutes.
            </p>
          </div>

          <button
            onClick={onRefreshTokens}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 light:bg-slate-100 light:border-slate-300 light:text-slate-800 transition-all"
          >
            <RefreshCw className="w-4 h-4 text-cyan-400" />
            <span>Refresh Queue</span>
          </button>
        </div>
      </div>

      {/* Main Grid: Queue List on Left, Active Patient Summary on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* ================= LEFT COLUMN: PATIENT QUEUE (4 Cols) ================= */}
        <div className="lg:col-span-4 space-y-3">
          <div className="flex items-center justify-between px-1">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Queued Patients ({tokens.length})
            </span>
            <span className="text-[11px] text-slate-500">Click to load</span>
          </div>

          <div className="space-y-2.5 max-h-[600px] overflow-y-auto pr-1">
            {tokens.length === 0 ? (
              <div className="p-8 text-center text-xs text-slate-500 rounded-2xl border border-slate-800">
                No patients currently waiting in queue.
              </div>
            ) : (
              tokens.map((t) => {
                const isSelected = selectedToken?.token_id === t.token_id;
                const isRedFlag = t.red_flag_alert || t.triage_color === 'red';

                return (
                  <button
                    key={t.token_id}
                    onClick={() => handleSelect(t)}
                    className={`w-full p-3.5 rounded-2xl border text-left transition-all relative overflow-hidden ${
                      isSelected
                        ? 'bg-slate-850 border-cyan-500 shadow-md ring-1 ring-cyan-500/40 light:bg-cyan-50 light:border-cyan-500'
                        : isRedFlag
                          ? 'bg-rose-950/20 border-rose-500/40 hover:bg-rose-950/30 light:bg-rose-50'
                          : 'bg-slate-900/40 border-slate-800 hover:border-slate-700 light:bg-white light:border-slate-200'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="font-mono font-black text-xs text-cyan-400 light:text-cyan-700">
                        {t.token_id}
                      </span>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        isRedFlag
                          ? 'bg-rose-500 text-white animate-pulse'
                          : t.triage_color === 'amber'
                            ? 'bg-amber-500/20 text-amber-300 light:bg-amber-100 light:text-amber-800'
                            : 'bg-emerald-500/20 text-emerald-300 light:bg-emerald-100 light:text-emerald-800'
                      }`}>
                        {t.triage_priority}
                      </span>
                    </div>

                    <div className="font-bold text-sm text-slate-100 light:text-slate-900 truncate">
                      {t.name}
                    </div>

                    <div className="text-xs text-slate-400 light:text-slate-600 truncate mt-0.5">
                      {t.chief_complaint} • {t.duration}
                    </div>

                    <div className="flex items-center justify-between text-[11px] text-slate-500 mt-2 pt-2 border-t border-slate-800/60 light:border-slate-100">
                      <span>{t.age}y / {t.gender}</span>
                      <span>{t.timestamp}</span>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </div>

        {/* ================= RIGHT COLUMN: CLINICAL DETAIL CARD (8 Cols) ================= */}
        <div className="lg:col-span-8">
          {selectedToken ? (
            <div className="p-6 rounded-3xl border bg-slate-900/60 border-slate-800 light:bg-white light:border-slate-200 shadow-2xl space-y-5">
              
              {/* Patient Banner */}
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 light:border-slate-200 pb-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono font-black text-cyan-400 bg-cyan-950/40 px-2 py-0.5 rounded-lg border border-cyan-800/30">
                      {selectedToken.token_id}
                    </span>
                    <span className="text-xs text-slate-400">Time: {selectedToken.timestamp}</span>
                  </div>
                  <h3 className="text-xl sm:text-2xl font-black text-white light:text-slate-900 mt-1">
                    {selectedToken.name}
                  </h3>
                  <div className="text-xs text-slate-400 light:text-slate-600">
                    Age / Gender: <span className="text-slate-200 light:text-slate-800 font-semibold">{selectedToken.age} yrs / {selectedToken.gender}</span>
                    {selectedToken.abha_id && (
                      <span className="ml-3 font-mono text-cyan-400">ABHA: {selectedToken.abha_id}</span>
                    )}
                  </div>
                </div>

                <span className={`px-3 py-1 rounded-xl text-xs font-bold ${
                  selectedToken.triage_color === 'red' || selectedToken.red_flag_alert
                    ? 'bg-rose-500/20 text-rose-400 border border-rose-500/40'
                    : 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40'
                }`}>
                  {selectedToken.triage_priority}
                </span>
              </div>

              {/* Emergency Alert Banner if red flag */}
              {(selectedToken.red_flag_alert || selectedToken.triage_color === 'red') && (
                <div className="p-3.5 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-300 light:text-rose-800 flex items-center gap-2.5 text-xs font-semibold">
                  <ShieldAlert className="w-5 h-5 text-rose-400 shrink-0" />
                  <span>ALERT: Red-Flag emergency screening positive. Check ABC vitals immediately!</span>
                </div>
              )}

              {/* Structured Clinical Intake Summary */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-3.5 rounded-2xl bg-slate-800/40 border border-slate-700/60 light:bg-slate-50 light:border-slate-200 space-y-1 text-xs">
                  <span className="text-slate-400 font-medium">Chief Presenting Complaint</span>
                  <div className="text-sm font-bold text-slate-100 light:text-slate-900">
                    {selectedToken.chief_complaint}
                  </div>
                  <div className="text-slate-400">
                    Duration: <span className="text-slate-200 light:text-slate-800 font-semibold">{selectedToken.duration}</span>
                  </div>
                  <div className="text-slate-400">
                    Reported Severity: <span className="text-slate-200 light:text-slate-800 font-semibold">{selectedToken.severity}</span>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-slate-800/40 border border-slate-700/60 light:bg-slate-50 light:border-slate-200 space-y-1 text-xs">
                  <span className="text-slate-400 font-medium">Patient Therapy Preference</span>
                  <div className="text-sm font-bold text-cyan-300 light:text-cyan-800">
                    {selectedToken.preferred_pathy}
                  </div>
                  <div className="text-slate-400">
                    Integrated ABDM Profile: <span className="text-emerald-400 font-semibold">Verified</span>
                  </div>
                  <div className="text-slate-400">
                    Previous Visits: <span className="text-slate-200 light:text-slate-800">First-mile Kiosk Intake</span>
                  </div>
                </div>
              </div>

              {/* Pre-Generated Cross-Pathy Suggestion Note */}
              <div className="p-4 rounded-2xl bg-cyan-950/20 border border-cyan-500/20 light:bg-cyan-50 text-xs space-y-1.5">
                <span className="font-bold text-cyan-400 light:text-cyan-800">
                  Pre-Triage Clinical Notes & Suggestions:
                </span>
                <p className="text-slate-300 light:text-slate-700">
                  {selectedToken.preliminary_notes}
                </p>
              </div>

              {/* Doctor Prescription & Notes Box */}
              <div className="space-y-2">
                <label className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Edit3 className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Physician Final Consultation Notes / Rx Overwrite:</span>
                </label>
                <textarea
                  rows={3}
                  value={physicianNotes}
                  onChange={(e) => setPhysicianNotes(e.target.value)}
                  placeholder="Type any custom dosage amendments, clinical findings, or lab test requests here..."
                  className="w-full p-3 rounded-2xl border bg-slate-800/50 border-slate-700 light:bg-slate-50 light:border-slate-300 text-slate-100 light:text-slate-900 text-xs outline-none focus:border-cyan-500"
                ></textarea>
              </div>

              {/* Consultation Status Banner */}
              {consultationDone && (
                <div className="p-3 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Consultation concluded. Prescription synced with patient ABHA Health Locker.</span>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-750 text-slate-200 border border-slate-700 light:bg-slate-100 light:border-slate-300 light:text-slate-800 transition-all"
                >
                  <Printer className="w-4 h-4 text-cyan-400" />
                  <span>Print OPD Case Sheet</span>
                </button>

                <button
                  onClick={handleFinishConsult}
                  className="flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-white shadow-lg shadow-emerald-500/25 active:scale-95 transition-all"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Accept, Prescribe & Complete</span>
                </button>
              </div>

            </div>
          ) : (
            <div className="p-16 text-center text-slate-500 border border-slate-800 rounded-3xl">
              Select a queued patient from the left column.
            </div>
          )}
        </div>

      </div>

    </div>
  );
}
